### ISSUE TITLE
Default Clan option in Settings

### ISSUE THREAD

**Issue by BarelyFunctionalCode** [SMaloney2017/Temple-OSRS-Plugin#2]
Hey,

It would probably be a good idea to have an option in the settings (going along with the clan edit token) for a default clan ID, then when you open the TempleOSRS sidebar it would default to that Clan with you select the Clan tab. I only say this because I keep forgetting my Clan ID and have to look it up on TempleOSRS, which ends up defeating the purpose of the plugin haha.

Awesome work, keep it up!

**Comment by SMaloney2017** [comment]
This sounds good,
I was planning on adding options to set a favorite-group/ watched-competition within the config settings but have been a little side tracked IRL. I like your idea of defaulting the tab on startup given a default-id is set. I will definitely implement this idea this afternoon and hopefully make a PR by tomorrow! Thanks again 😁

**Comment by SMaloney2017** [comment]
This ended up being super simple so I've already made the PR to RuneLite's plugin-hub. It should be updated soon!

I've added config options for `default-clan` and `default-competition` which, *given an ID set*, will fetch on startup. I also added the ability to *double-click* a tab's **search-icon** to load the default ID, similar to how the rank's tab works.
