### ISSUE TITLE
Add toggle for auto updater

### ISSUE THREAD

**Issue by SaffiCauthon** [SMaloney2017/Temple-OSRS-Plugin#3]
While I appreciate the ability and use of the API to auto-update users, I've specifically ensured that this process was disabled in the XP updater plugin and have been pulling my hair as to why I've been auto-updating.

I think it may be wise to remove this and have other users use the plugin you are calling the config for, or to add a toggle in the configuration menu.

https://github.com/SMaloney2017/Temple-OSRS-Plugin/commit/08c4372caa3055acd37443126dbc0f9e1d388690

**Comment by SMaloney2017** [comment]
Hey, Thanks! I will definitely add a toggle for this feature in the config by the next update. It should be simple enough.

Sorry about that by the way, I should have considered that not everyone would want their accounts auto-updated!

**Comment by SMaloney2017** [comment]
PR made with this change as well as all of those we've talked about previously! The plugin should be updated on the plugin-hub soon.
